### PR TITLE
Feature Auto Login (in conjunction with direct login feature)

### LINKED ISSUE #49: Auto Login
We suggest a auto login feature in combination with the "disable direct login url setting", which bypass the default login page and redirects instead to the login page of the OIDC login provider.

In combination with the suggested auto-linking feature ( https://github.com/dominik-th/matomo-plugin-LoginOIDC/issues/44, https://github.com/dominik-th/matomo-plugin-LoginOIDC/pull/45), this could help to improve the "single sign on" scenario.

### PR DESCRIPTION
**Pull request by ghost**
fixes https://github.com/dominik-th/matomo-plugin-LoginOIDC/issues/49

### CODE REVIEW

**Comment by ghost** [comment]
Is there anything I can do to help with reviewing / evaluating this PR?

**Comment by ghost** [comment]
Is there anything I can do to help with reviewing / evaluating this PR?

**Comment by ghost** [comment]
Is there anything I can do to help with reviewing / evaluating this PR?

**Comment by scott-amgen** [comment]
@DonCarlosGraz Beautiful feature, sadly the feature doesn't work on latest 4.12.3.

Issue #81 still stands.

**Comment by scott-amgen** [comment]
Not related to auto-login, but I've been able to workaround #81 with #83.

When I logged the events, I noticed with the current Login & LoginOIDC plugins, when an unauthenticated user visits an auth-required page, the user will get bounced around Login:login and LoginOIDC:loginMod until 500/403.

**Comment by ghost** [comment]
Since there is no activity anymore, I guess this pull request will not be accepted?

(Otherwise I will close the PR)

**Pull request closed without merging**
